export const LIGHT_THEME: THEME = {
  SHAPE: "#FFFFFF",
  BG_CARD: "#F7F7F7",
  PRIMARY: "#242E42",
  SECONDARY: "#4CE5B1",
  TERTIARY: "#4252FF",
  SUB_TEXT_COLOR: "#C8C7CC",
  BORDER: "#EFEFF4",
};
